usb: ehci-imx6: fix compilation errors
Fixed the following errors:
  drivers/usb/host/ehci-mx6.c: In function ‘ehci_hcd_init’:
  drivers/usb/host/ehci-mx6.c:144:32: error: ‘phy_bases’ undeclared (first use in this function)
  144 |         if (index < ARRAY_SIZE(phy_bases))

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>
(cherry picked from commit b12d35ac0ab0d682585ec978d152142991b01bfe)